/*
 *  Copyright (c) 2015 Michal Ďuračík
 */

package sk.uniza.duracik2.ImgSteganography;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Unlink
 */
public class Frame extends javax.swing.JFrame {
	
	private static final int TYPE_TEXT = 1;
	private static final int TYPE_FILE = 2;
	
	private File aFile;

    /** Creates new form Frame */
    public Frame() {
        initComponents();
		fileOpener1.setFilter(new FileNameExtensionFilter("Obrázky", ImageIO.getReaderFileSuffixes()));
		setLocationRelativeTo(null);
		fileOpener1.addFileOpenListener((ActionEvent paE) -> {
			aFile = null;
			if (fileOpener1.getFile() != null) {
				imageThumbnailer1.setImgFile(fileOpener1.getFile());
				jButton1.setEnabled(true);
				jButton3.setEnabled(true);
				//Len png a bmp su bezstratové, takže ich môžme dekodovať
				jButton2.setEnabled(
					fileOpener1.getFile().getName().endsWith(".png") 
					|| fileOpener1.getFile().getName().endsWith(".bmp")
				);
			}
			else {
				jButton1.setEnabled(false);
				jButton2.setEnabled(false);
				jButton3.setEnabled(false);
			}
		});
		jTextArea1.getDocument().addDocumentListener(new DocumentListener() {

			@Override
			public void insertUpdate(DocumentEvent paE) {
				jLabel3.setText(jTextArea1.getDocument().getLength()+"");
			}

			@Override
			public void removeUpdate(DocumentEvent paE) {
				jLabel3.setText(jTextArea1.getDocument().getLength()+"");
			}

			@Override
			public void changedUpdate(DocumentEvent paE) {
				jLabel3.setText(jTextArea1.getDocument().getLength()+"");
			}
		});
		
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        fileOpener1 = new sk.uniza.duracik2.ImgSteganography.FileOpener();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        imageThumbnailer1 = new sk.uniza.duracik2.ImgSteganography.ImageThumbnailer();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Image Steganography");

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(350);

        jLabel1.setText("Password:");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Write");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Read");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabel3.setText("0");

        jButton3.setText("Add File");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField1))
                    .addComponent(fileOpener1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(fileOpener1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jLabel2.setText("Náhľad:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(213, Short.MAX_VALUE))
                    .addComponent(imageThumbnailer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageThumbnailer1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		try {
			ImgSteganograph chiper = new ImgSteganograph(fileOpener1.getFile());
			
			byte[] message;
			
			if (aFile == null) {
				byte[] content = jTextArea1.getText().getBytes("UTF-8");
				message = new byte[content.length+1];
				message[0] = TYPE_TEXT;
				System.arraycopy(content, 0, message, 1, content.length);
			}
			else {
				byte[] fileContent = readFile(aFile);
				byte[] fileName = aFile.getName().getBytes("UTF-8");
				message = new byte[5+fileName.length+fileContent.length];
				message[0] = TYPE_FILE;
				message[1] = (byte) (fileName.length >> 24);
				message[2] = (byte) (fileName.length >> 16);
				message[3] = (byte) (fileName.length >> 8);
				message[4] = (byte) fileName.length;
				System.arraycopy(fileName, 0, message, 5, fileName.length);
				System.arraycopy(fileContent, 0, message, 5+fileName.length, fileContent.length);
			}
			
			if (!chiper.encrypt(jPasswordField1.getPassword(), message)) {
				JOptionPane.showMessageDialog(this, "Vyberte prosím väčší obrázok");
				return;
			}
			JFileChooser jfc = new JFileChooser(fileOpener1.getFile().getParentFile());
			jfc.setFileFilter(new FileNameExtensionFilter("Png images", "png"));
			if (jfc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
				if (!jfc.getSelectedFile().getName().toLowerCase().endsWith(".png")) {
					jfc.setSelectedFile(new File(jfc.getSelectedFile().getAbsolutePath()+".png"));
				}
				chiper.save(jfc.getSelectedFile());
			}
		}
		catch (IOException | EncryptionException ex) {
			ex.printStackTrace();
			JOptionPane.showMessageDialog(this, "Nepodarilo sa zašifrovať text");
		}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		try {
			ImgSteganograph chiper = new ImgSteganograph(fileOpener1.getFile());
			byte[] message = chiper.decrypt(jPasswordField1.getPassword());
			if (message != null) {
				if (message[0] == TYPE_TEXT) {
					jTextArea1.setText(new String(message, 1, message.length-1, "UTF-8"));
				}
				else {
					int fileNameLength = message[4];
					fileNameLength += message[3] << 8;
					fileNameLength += message[2] << 16;
					fileNameLength += message[1] << 24;
					byte[] fileName = new byte[fileNameLength];
					System.arraycopy(message, 5, fileName, 0, fileNameLength);
					jTextArea1.setText("Súbor: \n\t"+new String(fileName));
					JFileChooser jfc = new JFileChooser();
					jfc.setSelectedFile(new File(new String(fileName)));
					if (jfc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
						File f = jfc.getSelectedFile();
						try(FileOutputStream fos = new FileOutputStream(f)) {
							fos.write(message, 5+fileNameLength, message.length-5-fileNameLength);
						}
						catch (IOException ex) {
							//pass
						}
					}
				}
			}
			else {
				JOptionPane.showMessageDialog(this, "Nepodarilo sa prečítať text");
			}
		}
		catch (IOException | EncryptionException ex) {
			JOptionPane.showMessageDialog(this, "Nepodarilo sa prečítať text, zlé heslo?");
		}
		
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		JFileChooser jfc = new JFileChooser();
		if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
			aFile = jfc.getSelectedFile();
			jTextArea1.setText("Súbor: \n\t"+aFile.getName());
		}
		else {
			aFile = null;
			jTextArea1.setText("");
		}
    }//GEN-LAST:event_jButton3ActionPerformed

	private byte[] readFile(File paFile) {
		try {
			RandomAccessFile f = new RandomAccessFile(paFile, "r");
			byte[] b = new byte[(int)f.length()];
			f.read(b);
			return b;
		}
		catch (IOException ex) {
			return new byte[0];
		}
	}
	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the System look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		try {
			javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sk.uniza.duracik2.ImgSteganography.FileOpener fileOpener1;
    private sk.uniza.duracik2.ImgSteganography.ImageThumbnailer imageThumbnailer1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
